// <auto-generated />
using ApiRest.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ApiRest.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ApiRest.Models.Comuna", b =>
                {
                    b.Property<int>("CodRegion")
                        .HasColumnType("int");

                    b.Property<int>("CodProvincia")
                        .HasColumnType("int");

                    b.Property<int>("CodComuna")
                        .HasColumnType("int");

                    b.Property<string>("NombreComuna")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CodRegion", "CodProvincia", "CodComuna");

                    b.ToTable("Comuna");
                });

            modelBuilder.Entity("ApiRest.Models.Producto", b =>
                {
                    b.Property<int>("CodProducto")
                        .HasColumnType("int");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NombreProducto")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Precio")
                        .HasColumnType("int");

                    b.HasKey("CodProducto");

                    b.ToTable("Producto");
                });

            modelBuilder.Entity("ApiRest.Models.Provincia", b =>
                {
                    b.Property<int>("CodRegion")
                        .HasColumnType("int");

                    b.Property<int>("CodProvincia")
                        .HasColumnType("int");

                    b.Property<string>("NombreProvincia")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CodRegion", "CodProvincia");

                    b.ToTable("Provincia");
                });

            modelBuilder.Entity("ApiRest.Models.Region", b =>
                {
                    b.Property<int>("CodRegion")
                        .HasColumnType("int");

                    b.Property<string>("NombreRegion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CodRegion");

                    b.ToTable("Region");
                });

            modelBuilder.Entity("ApiRest.Models.Stock", b =>
                {
                    b.Property<int>("CodStock")
                        .HasColumnType("int");

                    b.Property<int>("Cantidad")
                        .HasColumnType("int");

                    b.Property<int>("CodProducto")
                        .HasColumnType("int");

                    b.Property<int>("CodSucursal")
                        .HasColumnType("int");

                    b.HasKey("CodStock");

                    b.HasIndex("CodProducto");

                    b.HasIndex("CodSucursal");

                    b.ToTable("Stock");
                });

            modelBuilder.Entity("ApiRest.Models.Sucursal", b =>
                {
                    b.Property<int>("CodSucursal")
                        .HasColumnType("int");

                    b.Property<int>("CodComuna")
                        .HasColumnType("int");

                    b.Property<int>("CodProvincia")
                        .HasColumnType("int");

                    b.Property<int>("CodRegion")
                        .HasColumnType("int");

                    b.Property<string>("Direccion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CodSucursal");

                    b.HasIndex("CodRegion", "CodProvincia", "CodComuna");

                    b.ToTable("Sucursal");
                });

            modelBuilder.Entity("ApiRest.Models.Tarjeta", b =>
                {
                    b.Property<string>("CodTransaccion")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("NombreTransaccion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("NumTarjeta")
                        .HasColumnType("int");

                    b.HasKey("CodTransaccion");

                    b.ToTable("Tarjeta");
                });

            modelBuilder.Entity("ApiRest.Models.Comuna", b =>
                {
                    b.HasOne("ApiRest.Models.Provincia", "Provincia")
                        .WithMany("Comuna")
                        .HasForeignKey("CodRegion", "CodProvincia")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Provincia");
                });

            modelBuilder.Entity("ApiRest.Models.Provincia", b =>
                {
                    b.HasOne("ApiRest.Models.Region", "Region")
                        .WithMany("Provincia")
                        .HasForeignKey("CodRegion")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Region");
                });

            modelBuilder.Entity("ApiRest.Models.Stock", b =>
                {
                    b.HasOne("ApiRest.Models.Producto", "Producto")
                        .WithMany("Stock")
                        .HasForeignKey("CodProducto")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ApiRest.Models.Sucursal", "Sucursal")
                        .WithMany("Stock")
                        .HasForeignKey("CodSucursal")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Producto");

                    b.Navigation("Sucursal");
                });

            modelBuilder.Entity("ApiRest.Models.Sucursal", b =>
                {
                    b.HasOne("ApiRest.Models.Comuna", "Comuna")
                        .WithMany("Sucursal")
                        .HasForeignKey("CodRegion", "CodProvincia", "CodComuna")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Comuna");
                });

            modelBuilder.Entity("ApiRest.Models.Comuna", b =>
                {
                    b.Navigation("Sucursal");
                });

            modelBuilder.Entity("ApiRest.Models.Producto", b =>
                {
                    b.Navigation("Stock");
                });

            modelBuilder.Entity("ApiRest.Models.Provincia", b =>
                {
                    b.Navigation("Comuna");
                });

            modelBuilder.Entity("ApiRest.Models.Region", b =>
                {
                    b.Navigation("Provincia");
                });

            modelBuilder.Entity("ApiRest.Models.Sucursal", b =>
                {
                    b.Navigation("Stock");
                });
#pragma warning restore 612, 618
        }
    }
}
